Repository replicatedhq/troubleshoot.sh, pull requests merged in 2022-08, with the labels that each got.

#407 Change uri prop to url
  docs/source/collect/http.md
Labels: type::bug, bug::normal

#408 Fix typos
  docs/source/redact/redactors.md
Labels: type::chore

#410 run commands in a shell
  docs/source/host-collect-analyze/run.md
Labels: type::docs
