Repository replicatedhq/troubleshoot.sh, pull requests merged in 2023-03, with the labels that each got.

#479 feat: support for rhel 9 variants (rhel, centos, ol, rocky)
  docs/source/host-collect-analyze/systemPackages.md
Labels: type::feature

#473 Adding docs around the Subnet Available collector and analyzer
  docs/gatsby-config.js
  docs/source/host-collect-analyze/all.md
  docs/source/host-collect-analyze/subnetAvailable.md
Labels: type::feature

#475 auto label new PRs with type::feature and type::docs
  .github/workflows/auto-label.yml
Labels: type::chore

#485 chore: Add missing mssql collector and analyser to TOC
  docs/gatsby-config.js
Labels: type::feature, type::docs
