Repository replicatedhq/troubleshoot.sh, pull requests merged in 2024-10, with the labels that each got.

#583 feat: add doc on cpu feature check
  docs/source/host-collect-analyze/cpu.md
Labels: type::feature

#582 feat(doc): explain runHostCollectorsInPod and add example for multiple host os analyzer result
  docs/source/host-collect-analyze/hostOS.md
  docs/source/support-bundle/supportbundle.md
Labels: type::feature

#586 feat: added spec to check cpu arch
  docs/source/host-collect-analyze/cpu.md
Labels: type::feature, type::docs

#587 Docs update for runHostCollectorsInPod
  docs/source/host-collect-analyze/overview.md
  docs/source/support-bundle/supportbundle.md
Labels: type::chore, type::docs

#584 document new http collector params
  docs/source/collect/http.md
Labels: type::feature

#567 chore: Add some minor grammatical fixes to metrics analyzer
  docs/source/analyze/node-metrics.md
Labels: type::chore

#585 Add note about image param
  docs/source/collect/goldpinger.md
Labels: type::feature

#566 feat: Document control groups collector
  docs/gatsby-config.js
  docs/source/host-collect-analyze/cgroups.md
Labels: type::feature

#588 doc: update doc on collecting multiple specs with runHostCollectorsInPod flag
  docs/source/support-bundle/collecting.md
Labels: type::chore, type::docs

#589 chore: gerard/sc-112634/remote-included-resources
  docs/source/host-collect-analyze/hostOS.md
  docs/source/host-collect-analyze/overview.md
Labels: type::chore, type::docs
