Repository replicatedhq/troubleshoot.sh, pull requests merged in 2024-04, with the labels that each got.

#553 feat: distribution analyzer support for kind
  docs/source/analyze/distribution.md
Labels: type::feature

#552 feat: add kubernetes node metrics collector and analyser
  docs/gatsby-config.js
  docs/source/analyze/node-metrics.md
  docs/source/analyze/outcomes.md
  docs/source/collect/node-metrics.md
Labels: type::feature, type::docs

#555 feat: Detect k0s distribution in analyzer
  docs/source/analyze/distribution.md
Labels: type::feature

#557 feat: Detect embedded clusters in distribution analyzer
  docs/source/analyze/distribution.md
Labels: type::feature

#558 chore: Add k0s tag in examples docs section
  analyzer-specs/cluster-is-k0s/preflight.yaml
  analyzer-specs/cluster-is-k0s/support-bundle.yaml
Labels: type::chore
