Repository replicatedhq/troubleshoot.sh, pull requests merged in 2025-02, with the labels that each got.

#604 feat: move http analyzer in right doc section
  docs/gatsby-config.js
  docs/source/analyze/http.md
  docs/source/host-collect-analyze/all.md
Labels: type::bug, bug::normal

#606 fix: js-yaml@3 to js-yaml@4 migration error
  generate-specs.js
  generate-specs/package.json
  package.json
Labels: type::bug, bug::normal, type::security

#608 fix: dependabot alerts
  gatsby-theme-marketing/gatsby-config.js
  gatsby-theme-marketing/package-lock.json
  gatsby-theme-marketing/package.json
  gatsby-theme-marketing/static/matomo.js
  gatsby-theme-troubleshoot/package-lock.json
  generate-specs.js
  package-lock.json
  yarn.lock
Labels: type::security

#605 chore: add node resources analyser example
  docs/source/analyze/node-resources.md
Labels: type::chore

#617 Docs for 'subnetContainsIP' collector and analyzer
  docs/source/host-collect-analyze/subnetcontainsip.md
Labels: type::feature

#618 fix broken schema link
  docs/source/analyze/analyzers.md
  docs/source/collect/collectors.md
  docs/source/support-bundle/supportbundle.md
Labels: type::bug, bug::normal

#619 add subnetcontainsip link to overview
  docs/gatsby-config.js
  docs/source/host-collect-analyze/all.md
  yarn.lock
Labels: type::feature
